name: Deploy using OIDC

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read    # REQUIRED to read repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP using OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/PROJECT_ID/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID
          service_account: github-deployer@PROJECT_ID.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve
