name: GCP OIDC Login Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/853245610917/locations/global/workloadIdentityPools/githubaction/providers/github-action
          service_account: terraform-sa@new-7d564.iam.gserviceaccount.com

      - name: Verify login
        run: |
          gcloud auth list
